<?php $form = $this->form; ?>
<style>
.popupLabel{
	display:inline;
	display:inline-block;
	width: 50px;
	padding: 5px;
}

.popupInput{
	display:inline;
	display:inline-block;
	padding: 5px;
}
.popupSubmit{
	margin-left: 115px;
	margin-top: 5px;
}
.textareaContent *{
	vertical-align: middle !important;
	resize:none;
}

.locationLabel{
	display:inline;
	display:inline-block;
	width: 50px;
	padding: 5px;	
}

.locationInput{
	display:inline;
	display:inline-block;
	padding: 5px;	
}

#load-locations{
	display: none;
}
</style>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/tinymce/js/tiny_mce.js"); ?>"></script>
<script type="text/javascript">
tinyMCE.init({
	// General options
	mode : "exact",
	elements : "ta1,ta2",
	theme : "advanced",
	plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave,visualblocks",

	// Theme options
	theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
	theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
	theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
	theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft,visualblocks",
	
	//plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,visualblocks",
	//plugins : "paste,pagebreak,table",
	
	// Theme options
	//theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,undo,redo,|,bullist,numlist,|,outdent,indent,blockquote,|,forecolor,backcolor,|,tablecontrols,|,hr",
	//theme_advanced_buttons1 : "formatselect,fontselect,fontsizeselect,|,forecolor,backcolor,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,code",
	//theme_advanced_buttons2 : "",
	//theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,ltr,rtl",
	//theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,pagebreak",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : true,

	// Example content CSS (should be your site CSS)
	content_css : "<?php echo $this->baseUrl("libs/tinymce/css/content.css"); ?>",

	// Drop lists for link/image/media/template dialogs
	template_external_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/template_list.js"); ?>",
	external_link_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/link_list.js"); ?>",
	external_image_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/image_list.js"); ?>",
	media_external_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/media_list.js"); ?>",

	// Style formats
	style_formats : [
		{title : 'Bold text', inline : 'b'},
		{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
		{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
		{title : 'Example 1', inline : 'span', classes : 'example1'},
		{title : 'Example 2', inline : 'span', classes : 'example2'},
		{title : 'Table styles'},
		{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
	],
	// Replace values for the template plugin
	template_replace_values : {
		username : "Some User",
		staffid : "991234"
	}
});
</script>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
          <td align="right"><h2><?php echo $this->language; ?></h2></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditEvent" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php echo $form->module_events_id->renderViewHelper(); ?>
	<?php echo $form->module_events_detail_id->renderViewHelper(); ?>
	<?php echo $form->language_id->renderViewHelper(); ?>
	<table style="margin:10px 0;">
		<tbody>
			<tr>
		    	<td><?php echo $form->title->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->title->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->start_date_time->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->start_date_time->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->end_date_time->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->end_date_time->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->description->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->description->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><label for="image"><?php echo $this->translate('Image:')?></label> </td>
		        <td>
		        	<input id="image" type="file" name="image" />
		        	<input id="image_path" type="hidden" name="image_path" value="<?php echo $this->image_path; ?>" />
		        	<img alt="" src="<?php echo $this->image_src;?>" style="max-width: 120px;" />
				</td>
			</tr>
			<tr>
				<td>
					<label>Event Location(s):</label>
				</td>
				<td>
					<div id="locationContainer">
						<div class="locationBox" id="record-1">
							<div class="textareaContent" style="float:left">
								<label for="textarea" style="vertical-align:top">Address</label>
								<textarea name="address[]" style="margin-left:20px"></textarea>
							</div>
							<div style="float:left">
								<div class="locationLabel"> 
									<label>City</label>
								</div>
								<div class="locationInput">
									<input name="city[]" type="text">
								</div>
							</div>
							<div style="float:left">
								<div class="locationLabel">
									<label>Plz</label>
								</div>
								<div class="locationInput">
									<input type="text" name="plz[]">
								</div>
							</div>
							<div class="locationDelete">
								<a class="deleteLocation">&nbsp;</a>
								<div class="deleteText">Delete Location</div>
							</div>
						</div>
					</div>	
					<div class="footer" style="clear:both">
						<a class="addEventLocation">Add Event Location</a>
						<a class="loadEventLocation">Load Event Location</a>
					</div>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->notes->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->notes->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->status->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->status->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		        <td colspan="3" align="center">
		        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
					<?php echo $form->reset->renderViewHelper() ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<div id="hiddenPopup" style="display:none">
	<div class="textareaContent">
		<label for="textarea" style="vertical-align:top">Address</label>
		<textarea name="popupTextarea" style="margin-left:20px" id="textarea"></textarea>
	</div>
	<div class="popupLabel">
		<label>City</label>
	</div>
	<div class="popupInput">
		<input type="text" name="popupCity">
	</div>
	<div class="popupLabel">
		<label>Plz</label>
	</div>
	<div class="popupInput">
		<input type="text" name="popupPlz">
	</div>
	<div class="popupSubmit">
		<input type="button" class="submitLocation" value="submit">
	</div>
</div>
<div id="load-locations">
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$('#start_date_time').datetimepicker({ 
		showOn: "both",
		buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
		buttonImageOnly: true,
		dateFormat: 'dd/mm/yy', 
		showSecond: false,
		timeFormat: 'hh:mm',
		firstDay:1
	});
	$('#end_date_time').datetimepicker({ 
		showOn: "both",
		buttonImage: "<?php echo $this->baseUrl("images/calander.png");?>",
		buttonImageOnly: true,
		dateFormat: 'dd/mm/yy', 
		showSecond: false,
		timeFormat: 'hh:mm',
		firstDay:1
	});
	$("#frmAddEditEvent").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Event...')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				if($('#image').attr("value")!="") {
					$.ajaxFileUpload({
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'image',
						dataType: 'json',
						data:{upload:'true'},
						success: function (data, status)
						{
							if(data.success != undefined) {
								$("#image_path").attr("value",data.success);
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("<?php echo $this->translate('Error uploading image.')?>");
							setTimeout(function(){
								promptus.close();
							}, 2000);
							
						}
					});
				} else {
					next();
				}
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize(),
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("<?php echo $this->translate('Event saved successfully.')?>");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"events","controller"=>"index","action" => "index"),"default",true);?>";
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
	$(".addEventLocation").on("click",function(){
		$("#hiddenPopup").dialog({
			modal:true,
			width:300,
			resizable:false,
			title:"Add Location"
		});
	});
	$(".submitLocation").on("click",function(){
		var rowNumber = $('.locationBox').length;
		var clonedLocationBox = $("#record-1").clone().attr("id","record-" + rowNumber);
		clonedLocationBox
		.find('input[name^=city]')
		.attr("value",$("input[name=popupCity]").attr("value"));
		
		clonedLocationBox
		.find('input[name^=plz]')
		.attr("value",$("input[name=popupPlz]").attr("value"));
		
		clonedLocationBox
		.find('textarea[name^=address]')
		.attr("value",$("textarea[name=popupTextarea]").attr("value"));

		$('#locationContainer').append(clonedLocationBox);
		$("#hiddenPopup").dialog("close");
	});

	$(".loadEventLocation").on("click",function(){
		var promptus = false;
    	var self = this;
		$(document).queue(function(next){
			promptus = new prompt({
            	reference : self,
                element : "#locationContainer",
                beforeShow : function(){
	                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Fetching Your Office Locations...'); ?>");
                }            
            });
            next();            
		}).queue(function(next){
	    	$.ajax({
	            url: "<?php echo $this->url(array("module"=>"events","controller"=>"index","action"=>"load-contacts")); ?>",
	            cache: false,
	            type: "POST",
	            success:function(data){
	            	$("#gridDialog").html(data).dialog({
						modal:true,
						width:500,
						resizable:false,
						title:"Add Location"
					});
	            	next();
	            }
	        });
	         
		}).queue(function(next){
			$(".importLoadedContacts").on("click",function(){
				alert("helloo");
			});
			promptus.close();
			next();
  		});
	});

});
// -->
function selectAll() {
	if($("#chkSelectAll").attr("checked") == "checked") {
		$(".contact").attr("checked","checked");
    } else {
    	$(".contact").removeAttr("checked");
    }
}
</script>
<div id="gridDialog">
</div>